# Generated by Django 4.2.3 on 2024-11-19 20:43

from django.db import migrations, models
import sajutoktok.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CERT_CODE',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('dt', models.CharField(help_text='YYYY-MM-DD HH:MM:SS', max_length=20)),
                ('method_type', models.CharField(help_text='email, tel', max_length=16)),
                ('method', models.CharField(help_text='user@email.com or 01012345678', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CHAT',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('from_id', models.CharField(max_length=64)),
                ('to_id', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('dt', models.CharField(help_text='YYYY-MM-DD HH:MM:SS', max_length=20)),
                ('read', models.CharField(help_text='y, n', max_length=1)),
                ('chat_type', models.CharField(help_text='image, item, purchase', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('post_id', models.CharField(max_length=16)),
                ('author_id', models.CharField(max_length=64)),
                ('parent_comment_id', models.CharField(blank=True, help_text='부모 댓글 아이디', max_length=16, null=True)),
                ('content', models.TextField()),
                ('dt', models.CharField(help_text='YYYY-MM-DD HH:MM:SS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ITEM',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('counselor_id', models.CharField(help_text='상담사 아이디', max_length=64)),
                ('name', models.CharField(help_text='상품명', max_length=64)),
                ('item_status', models.CharField(help_text='display, hide, soldout', max_length=20)),
                ('item_service', models.CharField(help_text='taro, saju, jum', max_length=20)),
                ('item_category', models.CharField(help_text='tel, chat, meet, cafe', max_length=20)),
                ('image', models.CharField(help_text='상품 이미지 경로', max_length=200)),
                ('description', models.TextField(help_text='상품 설명')),
                ('price', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LOG',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('log', models.TextField(help_text='시스템 로그 메세지')),
                ('dt', models.CharField(help_text='YYYY-MM-DD HH:MM:SS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NOTIFICATION',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('dt', models.CharField(help_text='YYYY-MM-DD HH:MM:SS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=64)),
                ('qna_counselor_id', models.CharField(blank=True, help_text='질문 게시글의 경우 상담사 아이디', max_length=64, null=True)),
                ('board', models.CharField(help_text='notice, event, qna, blog, faq', max_length=20)),
                ('images', models.TextField(blank=True, help_text='게시글 이미지 경로들(,로 구분)', null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('dt', models.CharField(help_text='YYYY-MM-DD HH:MM:SS', max_length=20)),
                ('view_count', models.CharField(help_text='조회수', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PURCHASE',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('counselor_id', models.CharField(max_length=64)),
                ('item_id', models.CharField(max_length=16)),
                ('price', models.CharField(max_length=60)),
                ('duration_seconds', models.CharField(help_text='상품 이용 시간(초)', max_length=20)),
                ('pgcode', models.CharField(help_text='item, point, adjust, pgcode', max_length=20)),
                ('cid', models.CharField(help_text='pg사 거래번호 또는 상담사 아이디', max_length=200)),
                ('tid', models.CharField(blank=True, help_text='pg사 거래번호', max_length=200, null=True)),
                ('status', models.CharField(help_text='pending, completed, reviewed, canceled, refunded', max_length=20)),
                ('log', models.TextField(blank=True, help_text='거래 메세지', null=True)),
                ('token', models.CharField(blank=True, help_text='pg사 거래 토큰', max_length=100, null=True)),
                ('dt', models.CharField(blank=True, help_text='YYYY-MM-DD HH:MM:SS', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='REVIEW',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('counselor_id', models.CharField(max_length=64)),
                ('payment_id', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('star', models.CharField(help_text='1~5', max_length=1)),
                ('dt', models.CharField(help_text='YYYY-MM-DD HH:MM:SS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SERVER_SETTING',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UPLOAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sajutoktok.models.upload_to)),
            ],
        ),
    ]
